#! /bin/sh

set -eu

git submodule update --init --recursive

dirs='
vim
upshell
password-store
tmux
macos-terminal
hg
cvs
git
'

mkdir -p ~/.cache
mkdir -p ~/.config

for stowdir in $dirs
do
   echo "Stowing $stowdir..."
   stow --target="$HOME" "$stowdir"
done
